version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/billing
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
